"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.conf import global_settings

# TEMPLATE_CONTEXT_PROCESSORS = global_settings.TEMPLATE_CONTEXT_PROCESSORS + (
#     'setting.context_processors.lang_context_processor',
# )


SUIT_CONFIG = {
    'ADMIN_NAME': 'NURAKSA TOUR',
    # 'MENU': (
    #     {'label': 'Words', 'icon': 'fa fa-file-o', 'app': 'word'},
    #     {'label': 'Authorization', 'icon': 'fa fa-lock', 'app': 'auth'},
    # ),
    'ADMIN_BRAND_NAME': 'NURAKSATOUR',
    'LIST_PER_PAGE': 18,
    'SEARCH_URL': '',
    'SHOW_REQUIRED_ASTERISK': True
}

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*s4b!2sy0#6(ishr0)&&(^nls5hn8v9t^z58so&!cq@!#8(&&c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admindocs',
    'django.contrib.humanize',
    'word',
    'wysiwyg',
    'mptt',
    'filemedia',
    'page',
    'appearance',
    'setting',
    'contact',
    'pront',
    # 'prontand',
)

LOCALE_PATHS = (
    os.path.join(os.path.dirname(__file__), "../locale"),
)

REDACTOR_OPTIONS = {}

REDACTOR_UPLOAD = 'image/'
# REDACTOR_UPLOAD_HANDLER = 'redactor.handlers.DateDirectoryUploader'
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

)

ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'setting.context_processors.general',
                'setting.context_processors.admin',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'nuraksatour',
        'USER': 'root',
        'PASSWORD': 'admin',
        'HOST': 'localhost',  # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'id'
LANGUAGE = (
    ('id', 'Indonesia'),
)
TIME_ZONE = 'Asia/Makassar'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = '/Users/antlink/PycharmProjects/DjangoProject/static/'
STATIC_URL = '/static/'

MEDIA_ROOT = '/Users/antlink/PycharmProjects/DjangoProject/media/'
MEDIA_URL = '/media/'
